--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/angga7togk/MydQuest
build-by-default: true
branches:
  - master
projects:
  MydQuest:
    path: ""
    libs:
      - src: Muqsit/InvMenu/Invmenu
        branch: "pm5"
        version: ^4.6.5
      - src: jojoe77777/FormAPI/libFormAPI
        branch: master
        version: ^2.1.1
      - src: poggit/libasynql/libasynql
        branch: master
        version: ^4.2.3
      - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy
        branch: master
        version: ^3.0.3
      - src: DaPigGuy/libPiggyUpdateChecker/libPiggyUpdateChecker
        branch: master
        version: ^1.0.0
      - src: xenialdan/apibossbar/apibossbar
        branch: pm5
        version: ^0.1.6
---

